JavasScript課題2を作成しました
yuki-manabi/js_kadai2 pull request #1
Opened 2021-03-29 16:27 UTC by yuki-manabi

コード作成しましたので、レビューをお願いいたします。

2021-03-30 10:56 UTC, myzktkyk requested changes
動作は問題ありませんでしたが、コードについて何点か指摘があります！

2021-03-30 10:56 UTC, myzktkyk commented on js_kadai2.html
>    <button onclick="displayResult()">実行</button>
こちらですが HTML 側で記載するのではなく Javascript 側で `addEventListener` を利用してイベントの設定をお願いしたいです。
HTML 側にイベントの記載があると HTML と Javascript の結合度が高まってしまうので、現場ではあまり用いられません。

2021-03-30 10:56 UTC, myzktkyk commented on js_kadai2.js
> +    if(regex.test(fizz) && regex.test(buzz)){
今の記述の通り「正しかったら後続の処理をする」という書き方をすると
エラー時の処理がかなり後ろに書かれることになり、見づらいコードになってしまいます。
エラーチェックは以下の記述例の通り「エラー時は即処理を打ち切って後続の処理を行わない」とする方が見やすくなります。

```suggestion
  if (!regex.test(fizz) || !regex.test(buzz)) {
    const pElement = document.createElement(`div`);
    pElement.classList.add("children");
    pElement.textContent = "整数値を入力してください";
    parentNode.appendChild(pElement);
    return;
  }
```

2021-03-30 14:15 UTC, yuki-manabi commented
@myzktkyk 
ご確認ありがとうございます。ご指摘部分を修正し、コミットいたしました。

2021-03-31 00:47 UTC, niganium reviewed
お疲れ様です。何点か指摘いたしました。修正したのち再度ご提出をお願いいたします。

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +  document.getElementById(`btn`).addEventListener(`click`, () => {
基本JSのクオーテーションはシングルクオーテーションとなるので、本課題ではシングルクオーテーションのご使用をお願いいたします。

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +    if(parentNode.getElementsByClassName(`children`).length > 0){
構文上ifと()の間にはスペースを設けます
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/if...else

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +      for(let i=1,j=1; i<100,j<100;){
for文にも()の間にスペースが入ります。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +        if(_fizzNum>=100 && _buzzNum>=100){
こちらのFizzBuzzを区別する計算式なのですが、
例えば for文などで使用される変数iに対して_fizzNumなどで割り切れるかの判定にすると少しシンプルになるかと思いました(こちら必須ではないため修正できそうであればお願いいたします)
https://qiita.com/kiubu/items/24cf3abf019028708d42

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +        const _fizzNum = fizzNum*i;
他変数同様２単語目から大文字になるキャメルケース宣言にしましょう。

2021-03-31 00:47 UTC, niganium commented on js_kadai2.js
> +          pElement.textContent = "Buzz " + _buzzNum;
文字列+変数を出力する際テンプレートリテラルが便利です。
基本JSで``のクオーテーションを用いる場面はテンプレートリテラル以外あまりないかと思います。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2021-03-31 03:50 UTC, yuki-manabi commented
上記指摘事項を修正し、コミットいたしました。

2021-03-31 11:34 UTC, myzktkyk requested changes
1点指摘をしております。

2021-03-31 11:34 UTC, myzktkyk commented on js_kadai2.js
> +    } else {
23 行目で `return` しているのでこの else は不要です。
なので以前提示した以下のサンプルでは中かっこで閉じてしまっています。

https://github.com/yuki-manabi/js_kadai2/pull/1#discussion_r603992441

2021-03-31 11:52 UTC, yuki-manabi commented
@myzktkyk 
ご確認ありがとうございます。elseにおけるレビューを修正いたしました。

2021-03-31 22:04 UTC, niganium reviewed
お疲れ様です。確認しました。
軽微な指摘となるため再提出は不要です。
修正をお願いいたします。

2021-03-31 22:04 UTC, niganium commented on js_kadai2.js
> +    const fizz = document.getElementById(`fizz`).value;
```pElement.textContent = `FizzBuzz ${i}`;```
のようなテンプレートリテラルを用いる以外では基本 '' のシングルクオーテーションを用いた方が良いと思います。
以下に例文が記載されています。参考までに。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/if...else

2021-04-01 03:40 UTC, yuki-manabi commented
@niganium 
ありがとうございます。修正いたしました。

2021-04-18 14:01 UTC, merged